data:
  '{{ rundir }}/anl.grib2': https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.{{ yyyymmdd }}/{{ hh }}/atmos/gfs.t{{ hh }}z.pgrb2.0p25.f000
hh: '{{ cycle.strftime("%H") }}'
rundir: '{{ runroot }}/05'
workflow:
  cycledef:
    - attrs:
        group: default
      spec: '{{ yyyymmddhhmm }} {{ yyyymmddhhmm }} 00:00:00'
  log:
    value: '{{ rundir }}/rocoto.log'
  tasks:
    task_ungrib:
      attrs:
        cycledefs: default
      account: '{{ account }}'
yyyymmdd: '{{ cycle.strftime("%Y%m%d") }}'
yyyymmddhhmm: '{{ cycle.strftime("%Y%m%d%H%M") }}'
